### PR TITLE
fail2ban for ssh

### LINKED ISSUE #430: Enable fail2ban for SSH
To make the CES less vulnerable to brute-force and DoS attacks on the SSH service, we want to install the fail2ban tool here and configure it to automatically block IPs with high numbers of failed access attempts for a while.

### PR DESCRIPTION
**Pull request by CloudFlo2312**
Resolves #430

### CODE REVIEW

File: images/scripts/commons/fail2ban.sh [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+# Configure fail2ban for sshd
+echo "configuring fail2ban for sshd"
+
+# Values are taken from default configuration
+fail2ban-client set sshd addignoreip 127.0.0.1/8
+fail2ban-client set sshd maxretry 5
+fail2ban-client set sshd findtime 10m
+fail2ban-client set sshd bantime 10m
+fail2ban-client set sshd addlogpath /var/log/auth.log
```
Comment (Subaro) [inline images/scripts/commons/fail2ban.sh:27]: It should be better emphasized in the docs that these values are the default for all new instances of ecosystems.

**Review by Subaro — CHANGES_REQUESTED** [review]

**Comment by Subaro** [comment]
Good changes with some minor documentation things to address. I still have a question about the use of SSH-based Applications, such as Github. Does fail2ban enforce RateLimiting or does it simply work on failed logins?

File: docs/operations/fail2ban_de.md [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+
+```
+fail2ban-client start
+```
+
+## Konfiguration
+
+fail2ban kann für verschiedene Serverdienste konfiguriert werden. Standardmäßig ist fail2ban im CES für die Überprüfung
+von ssh-Verbindungen aktiviert. Als Werte sind die Attribute `ignoreip`, `maxretry`, `findtime`, `bantime` und
+der `logpath` konfiguriert.
```
Comment (Subaro) [inline docs/operations/fail2ban_de.md:56]: Auf welche Werte werden diese gesetzt?

**Review by Subaro — APPROVED** [review]
